/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDealReportsRouteImport } from './routes/_app.deal-reports'
import { Route as AppDealsRouteImport } from './routes/_app.deals'
import { Route as AppEmailsRouteImport } from './routes/_app.emails'
import { Route as AppFormsRouteImport } from './routes/_app.forms'
import { Route as AppListsRouteImport } from './routes/_app.lists'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSegmentsRouteImport } from './routes/_app.segments'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTagsRouteImport } from './routes/_app.tags'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppWebsiteRouteImport } from './routes/_app.website'
import { Route as AppAutomationsIndexRouteImport } from './routes/_app.automations.index'
import { Route as AppAutomationsIdRouteImport } from './routes/_app.automations.$id'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app.companies.index'
import { Route as AppCompaniesIdRouteImport } from './routes/_app.companies.$id'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppDealsIndexRouteImport } from './routes/_app.deals.index'
import { Route as AppDealsIdRouteImport } from './routes/_app.deals.$id'
import { Route as AppEmailsIndexRouteImport } from './routes/_app.emails.index'
import { Route as AppEmailsArchiveRouteImport } from './routes/_app.emails.archive'
import { Route as AppEmailsTemplatesRouteImport } from './routes/_app.emails.templates'
import { Route as AppEmailsVariablesRouteImport } from './routes/_app.emails.variables'
import { Route as AppListsIndexRouteImport } from './routes/_app.lists.index'
import { Route as AppListsIdRouteImport } from './routes/_app.lists.$id'
import { Route as AppSegmentsIndexRouteImport } from './routes/_app.segments.index'
import { Route as AppSegmentsIdRouteImport } from './routes/_app.segments.$id'
import { Route as AppWebsiteIndexRouteImport } from './routes/_app.website.index'
import { Route as AppWebsiteAssetsRouteImport } from './routes/_app.website.assets'
import { Route as AppWebsiteFormsRouteImport } from './routes/_app.website.forms'
import { Route as AppWebsiteMessagesRouteImport } from './routes/_app.website.messages'
import { Route as AppWebsitePagesRouteImport } from './routes/_app.website.pages'
import { Route as AppWebsiteTrackingRouteImport } from './routes/_app.website.tracking'
import { Route as AppAutomationsBriefsIndexRouteImport } from './routes/_app.automations.briefs.index'
import { Route as AppAutomationsBriefsIdRouteImport } from './routes/_app.automations.briefs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDealReportsRoute = AppDealReportsRouteImport.update({
  id: '/deal-reports',
  path: '/deal-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsRoute = AppEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppListsRoute = AppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsRoute = AppSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteRoute = AppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsIndexRoute = AppAutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsIdRoute = AppAutomationsIdRouteImport.update({
  id: '/automations/$id',
  path: '/automations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const AppCompaniesIdRoute = AppCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCompaniesRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppDealsIdRoute = AppDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppEmailsIndexRoute = AppEmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppEmailsArchiveRoute = AppEmailsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppEmailsTemplatesRoute = AppEmailsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppEmailsVariablesRoute = AppEmailsVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppListsIndexRoute = AppListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppListsRoute,
} as any)
const AppListsIdRoute = AppListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppListsRoute,
} as any)
const AppSegmentsIndexRoute = AppSegmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSegmentsRoute,
} as any)
const AppSegmentsIdRoute = AppSegmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSegmentsRoute,
} as any)
const AppWebsiteIndexRoute = AppWebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteAssetsRoute = AppWebsiteAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteFormsRoute = AppWebsiteFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteMessagesRoute = AppWebsiteMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsitePagesRoute = AppWebsitePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteTrackingRoute = AppWebsiteTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppAutomationsBriefsIndexRoute =
  AppAutomationsBriefsIndexRouteImport.update({
    id: '/automations/briefs/',
    path: '/automations/briefs/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAutomationsBriefsIdRoute = AppAutomationsBriefsIdRouteImport.update({
  id: '/automations/briefs/$id',
  path: '/automations/briefs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/companies': typeof AppCompaniesRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/deal-reports': typeof AppDealReportsRoute
  '/deals': typeof AppDealsRouteWithChildren
  '/emails': typeof AppEmailsRouteWithChildren
  '/forms': typeof AppFormsRoute
  '/lists': typeof AppListsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/segments': typeof AppSegmentsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/tasks': typeof AppTasksRoute
  '/website': typeof AppWebsiteRouteWithChildren
  '/automations/$id': typeof AppAutomationsIdRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/emails/archive': typeof AppEmailsArchiveRoute
  '/emails/templates': typeof AppEmailsTemplatesRoute
  '/emails/variables': typeof AppEmailsVariablesRoute
  '/lists/$id': typeof AppListsIdRoute
  '/segments/$id': typeof AppSegmentsIdRoute
  '/website/assets': typeof AppWebsiteAssetsRoute
  '/website/forms': typeof AppWebsiteFormsRoute
  '/website/messages': typeof AppWebsiteMessagesRoute
  '/website/pages': typeof AppWebsitePagesRoute
  '/website/tracking': typeof AppWebsiteTrackingRoute
  '/automations/': typeof AppAutomationsIndexRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/deals/': typeof AppDealsIndexRoute
  '/emails/': typeof AppEmailsIndexRoute
  '/lists/': typeof AppListsIndexRoute
  '/segments/': typeof AppSegmentsIndexRoute
  '/website/': typeof AppWebsiteIndexRoute
  '/automations/briefs/$id': typeof AppAutomationsBriefsIdRoute
  '/automations/briefs/': typeof AppAutomationsBriefsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/deal-reports': typeof AppDealReportsRoute
  '/forms': typeof AppFormsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/tasks': typeof AppTasksRoute
  '/automations/$id': typeof AppAutomationsIdRoute
  '/companies/$id': typeof AppCompaniesIdRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/emails/archive': typeof AppEmailsArchiveRoute
  '/emails/templates': typeof AppEmailsTemplatesRoute
  '/emails/variables': typeof AppEmailsVariablesRoute
  '/lists/$id': typeof AppListsIdRoute
  '/segments/$id': typeof AppSegmentsIdRoute
  '/website/assets': typeof AppWebsiteAssetsRoute
  '/website/forms': typeof AppWebsiteFormsRoute
  '/website/messages': typeof AppWebsiteMessagesRoute
  '/website/pages': typeof AppWebsitePagesRoute
  '/website/tracking': typeof AppWebsiteTrackingRoute
  '/automations': typeof AppAutomationsIndexRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/deals': typeof AppDealsIndexRoute
  '/emails': typeof AppEmailsIndexRoute
  '/lists': typeof AppListsIndexRoute
  '/segments': typeof AppSegmentsIndexRoute
  '/website': typeof AppWebsiteIndexRoute
  '/automations/briefs/$id': typeof AppAutomationsBriefsIdRoute
  '/automations/briefs': typeof AppAutomationsBriefsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/companies': typeof AppCompaniesRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deal-reports': typeof AppDealReportsRoute
  '/_app/deals': typeof AppDealsRouteWithChildren
  '/_app/emails': typeof AppEmailsRouteWithChildren
  '/_app/forms': typeof AppFormsRoute
  '/_app/lists': typeof AppListsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/segments': typeof AppSegmentsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tags': typeof AppTagsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/website': typeof AppWebsiteRouteWithChildren
  '/_app/automations/$id': typeof AppAutomationsIdRoute
  '/_app/companies/$id': typeof AppCompaniesIdRoute
  '/_app/deals/$id': typeof AppDealsIdRoute
  '/_app/emails/archive': typeof AppEmailsArchiveRoute
  '/_app/emails/templates': typeof AppEmailsTemplatesRoute
  '/_app/emails/variables': typeof AppEmailsVariablesRoute
  '/_app/lists/$id': typeof AppListsIdRoute
  '/_app/segments/$id': typeof AppSegmentsIdRoute
  '/_app/website/assets': typeof AppWebsiteAssetsRoute
  '/_app/website/forms': typeof AppWebsiteFormsRoute
  '/_app/website/messages': typeof AppWebsiteMessagesRoute
  '/_app/website/pages': typeof AppWebsitePagesRoute
  '/_app/website/tracking': typeof AppWebsiteTrackingRoute
  '/_app/automations/': typeof AppAutomationsIndexRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
  '/_app/emails/': typeof AppEmailsIndexRoute
  '/_app/lists/': typeof AppListsIndexRoute
  '/_app/segments/': typeof AppSegmentsIndexRoute
  '/_app/website/': typeof AppWebsiteIndexRoute
  '/_app/automations/briefs/$id': typeof AppAutomationsBriefsIdRoute
  '/_app/automations/briefs/': typeof AppAutomationsBriefsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/onboarding'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/deal-reports'
    | '/deals'
    | '/emails'
    | '/forms'
    | '/lists'
    | '/reports'
    | '/segments'
    | '/settings'
    | '/tags'
    | '/tasks'
    | '/website'
    | '/automations/$id'
    | '/companies/$id'
    | '/deals/$id'
    | '/emails/archive'
    | '/emails/templates'
    | '/emails/variables'
    | '/lists/$id'
    | '/segments/$id'
    | '/website/assets'
    | '/website/forms'
    | '/website/messages'
    | '/website/pages'
    | '/website/tracking'
    | '/automations/'
    | '/companies/'
    | '/contacts/'
    | '/deals/'
    | '/emails/'
    | '/lists/'
    | '/segments/'
    | '/website/'
    | '/automations/briefs/$id'
    | '/automations/briefs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/onboarding'
    | '/dashboard'
    | '/deal-reports'
    | '/forms'
    | '/reports'
    | '/settings'
    | '/tags'
    | '/tasks'
    | '/automations/$id'
    | '/companies/$id'
    | '/deals/$id'
    | '/emails/archive'
    | '/emails/templates'
    | '/emails/variables'
    | '/lists/$id'
    | '/segments/$id'
    | '/website/assets'
    | '/website/forms'
    | '/website/messages'
    | '/website/pages'
    | '/website/tracking'
    | '/automations'
    | '/companies'
    | '/contacts'
    | '/deals'
    | '/emails'
    | '/lists'
    | '/segments'
    | '/website'
    | '/automations/briefs/$id'
    | '/automations/briefs'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/companies'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/deal-reports'
    | '/_app/deals'
    | '/_app/emails'
    | '/_app/forms'
    | '/_app/lists'
    | '/_app/reports'
    | '/_app/segments'
    | '/_app/settings'
    | '/_app/tags'
    | '/_app/tasks'
    | '/_app/website'
    | '/_app/automations/$id'
    | '/_app/companies/$id'
    | '/_app/deals/$id'
    | '/_app/emails/archive'
    | '/_app/emails/templates'
    | '/_app/emails/variables'
    | '/_app/lists/$id'
    | '/_app/segments/$id'
    | '/_app/website/assets'
    | '/_app/website/forms'
    | '/_app/website/messages'
    | '/_app/website/pages'
    | '/_app/website/tracking'
    | '/_app/automations/'
    | '/_app/companies/'
    | '/_app/contacts/'
    | '/_app/deals/'
    | '/_app/emails/'
    | '/_app/lists/'
    | '/_app/segments/'
    | '/_app/website/'
    | '/_app/automations/briefs/$id'
    | '/_app/automations/briefs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deal-reports': {
      id: '/_app/deal-reports'
      path: '/deal-reports'
      fullPath: '/deal-reports'
      preLoaderRoute: typeof AppDealReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emails': {
      id: '/_app/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AppEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists': {
      id: '/_app/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/segments': {
      id: '/_app/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AppSegmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website': {
      id: '/_app/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AppWebsiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations/': {
      id: '/_app/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AppAutomationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations/$id': {
      id: '/_app/automations/$id'
      path: '/automations/$id'
      fullPath: '/automations/$id'
      preLoaderRoute: typeof AppAutomationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/companies/$id': {
      id: '/_app/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AppCompaniesIdRouteImport
      parentRoute: typeof AppCompaniesRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/deals/$id': {
      id: '/_app/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AppDealsIdRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/emails/': {
      id: '/_app/emails/'
      path: '/'
      fullPath: '/emails/'
      preLoaderRoute: typeof AppEmailsIndexRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/emails/archive': {
      id: '/_app/emails/archive'
      path: '/archive'
      fullPath: '/emails/archive'
      preLoaderRoute: typeof AppEmailsArchiveRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/emails/templates': {
      id: '/_app/emails/templates'
      path: '/templates'
      fullPath: '/emails/templates'
      preLoaderRoute: typeof AppEmailsTemplatesRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/emails/variables': {
      id: '/_app/emails/variables'
      path: '/variables'
      fullPath: '/emails/variables'
      preLoaderRoute: typeof AppEmailsVariablesRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/lists/': {
      id: '/_app/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof AppListsIndexRouteImport
      parentRoute: typeof AppListsRoute
    }
    '/_app/lists/$id': {
      id: '/_app/lists/$id'
      path: '/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof AppListsIdRouteImport
      parentRoute: typeof AppListsRoute
    }
    '/_app/segments/': {
      id: '/_app/segments/'
      path: '/'
      fullPath: '/segments/'
      preLoaderRoute: typeof AppSegmentsIndexRouteImport
      parentRoute: typeof AppSegmentsRoute
    }
    '/_app/segments/$id': {
      id: '/_app/segments/$id'
      path: '/$id'
      fullPath: '/segments/$id'
      preLoaderRoute: typeof AppSegmentsIdRouteImport
      parentRoute: typeof AppSegmentsRoute
    }
    '/_app/website/': {
      id: '/_app/website/'
      path: '/'
      fullPath: '/website/'
      preLoaderRoute: typeof AppWebsiteIndexRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/assets': {
      id: '/_app/website/assets'
      path: '/assets'
      fullPath: '/website/assets'
      preLoaderRoute: typeof AppWebsiteAssetsRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/forms': {
      id: '/_app/website/forms'
      path: '/forms'
      fullPath: '/website/forms'
      preLoaderRoute: typeof AppWebsiteFormsRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/messages': {
      id: '/_app/website/messages'
      path: '/messages'
      fullPath: '/website/messages'
      preLoaderRoute: typeof AppWebsiteMessagesRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/pages': {
      id: '/_app/website/pages'
      path: '/pages'
      fullPath: '/website/pages'
      preLoaderRoute: typeof AppWebsitePagesRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/tracking': {
      id: '/_app/website/tracking'
      path: '/tracking'
      fullPath: '/website/tracking'
      preLoaderRoute: typeof AppWebsiteTrackingRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/automations/briefs/': {
      id: '/_app/automations/briefs/'
      path: '/automations/briefs'
      fullPath: '/automations/briefs/'
      preLoaderRoute: typeof AppAutomationsBriefsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations/briefs/$id': {
      id: '/_app/automations/briefs/$id'
      path: '/automations/briefs/$id'
      fullPath: '/automations/briefs/$id'
      preLoaderRoute: typeof AppAutomationsBriefsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCompaniesRouteChildren {
  AppCompaniesIdRoute: typeof AppCompaniesIdRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
}

const AppCompaniesRouteChildren: AppCompaniesRouteChildren = {
  AppCompaniesIdRoute: AppCompaniesIdRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
}

const AppCompaniesRouteWithChildren = AppCompaniesRoute._addFileChildren(
  AppCompaniesRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppDealsRouteChildren {
  AppDealsIdRoute: typeof AppDealsIdRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppDealsRouteChildren: AppDealsRouteChildren = {
  AppDealsIdRoute: AppDealsIdRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppDealsRouteWithChildren = AppDealsRoute._addFileChildren(
  AppDealsRouteChildren,
)

interface AppEmailsRouteChildren {
  AppEmailsArchiveRoute: typeof AppEmailsArchiveRoute
  AppEmailsTemplatesRoute: typeof AppEmailsTemplatesRoute
  AppEmailsVariablesRoute: typeof AppEmailsVariablesRoute
  AppEmailsIndexRoute: typeof AppEmailsIndexRoute
}

const AppEmailsRouteChildren: AppEmailsRouteChildren = {
  AppEmailsArchiveRoute: AppEmailsArchiveRoute,
  AppEmailsTemplatesRoute: AppEmailsTemplatesRoute,
  AppEmailsVariablesRoute: AppEmailsVariablesRoute,
  AppEmailsIndexRoute: AppEmailsIndexRoute,
}

const AppEmailsRouteWithChildren = AppEmailsRoute._addFileChildren(
  AppEmailsRouteChildren,
)

interface AppListsRouteChildren {
  AppListsIdRoute: typeof AppListsIdRoute
  AppListsIndexRoute: typeof AppListsIndexRoute
}

const AppListsRouteChildren: AppListsRouteChildren = {
  AppListsIdRoute: AppListsIdRoute,
  AppListsIndexRoute: AppListsIndexRoute,
}

const AppListsRouteWithChildren = AppListsRoute._addFileChildren(
  AppListsRouteChildren,
)

interface AppSegmentsRouteChildren {
  AppSegmentsIdRoute: typeof AppSegmentsIdRoute
  AppSegmentsIndexRoute: typeof AppSegmentsIndexRoute
}

const AppSegmentsRouteChildren: AppSegmentsRouteChildren = {
  AppSegmentsIdRoute: AppSegmentsIdRoute,
  AppSegmentsIndexRoute: AppSegmentsIndexRoute,
}

const AppSegmentsRouteWithChildren = AppSegmentsRoute._addFileChildren(
  AppSegmentsRouteChildren,
)

interface AppWebsiteRouteChildren {
  AppWebsiteAssetsRoute: typeof AppWebsiteAssetsRoute
  AppWebsiteFormsRoute: typeof AppWebsiteFormsRoute
  AppWebsiteMessagesRoute: typeof AppWebsiteMessagesRoute
  AppWebsitePagesRoute: typeof AppWebsitePagesRoute
  AppWebsiteTrackingRoute: typeof AppWebsiteTrackingRoute
  AppWebsiteIndexRoute: typeof AppWebsiteIndexRoute
}

const AppWebsiteRouteChildren: AppWebsiteRouteChildren = {
  AppWebsiteAssetsRoute: AppWebsiteAssetsRoute,
  AppWebsiteFormsRoute: AppWebsiteFormsRoute,
  AppWebsiteMessagesRoute: AppWebsiteMessagesRoute,
  AppWebsitePagesRoute: AppWebsitePagesRoute,
  AppWebsiteTrackingRoute: AppWebsiteTrackingRoute,
  AppWebsiteIndexRoute: AppWebsiteIndexRoute,
}

const AppWebsiteRouteWithChildren = AppWebsiteRoute._addFileChildren(
  AppWebsiteRouteChildren,
)

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRouteWithChildren
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDealReportsRoute: typeof AppDealReportsRoute
  AppDealsRoute: typeof AppDealsRouteWithChildren
  AppEmailsRoute: typeof AppEmailsRouteWithChildren
  AppFormsRoute: typeof AppFormsRoute
  AppListsRoute: typeof AppListsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSegmentsRoute: typeof AppSegmentsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWebsiteRoute: typeof AppWebsiteRouteWithChildren
  AppAutomationsIdRoute: typeof AppAutomationsIdRoute
  AppAutomationsIndexRoute: typeof AppAutomationsIndexRoute
  AppAutomationsBriefsIdRoute: typeof AppAutomationsBriefsIdRoute
  AppAutomationsBriefsIndexRoute: typeof AppAutomationsBriefsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRouteWithChildren,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDealReportsRoute: AppDealReportsRoute,
  AppDealsRoute: AppDealsRouteWithChildren,
  AppEmailsRoute: AppEmailsRouteWithChildren,
  AppFormsRoute: AppFormsRoute,
  AppListsRoute: AppListsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSegmentsRoute: AppSegmentsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWebsiteRoute: AppWebsiteRouteWithChildren,
  AppAutomationsIdRoute: AppAutomationsIdRoute,
  AppAutomationsIndexRoute: AppAutomationsIndexRoute,
  AppAutomationsBriefsIdRoute: AppAutomationsBriefsIdRoute,
  AppAutomationsBriefsIndexRoute: AppAutomationsBriefsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
