export const handwrittenFileLineLimit = 500;
export const clientFunctionLineLimit = 250;
export const task6HotspotFileLineLimit = 250;
export const task6HotspotFunctionLineLimit = 120;
// Generated by TanStack Router. Exact paths prevent a `.gen.*` rename from
// bypassing dependency, parser, file-size, and function-size enforcement.
export const generatedSourcePaths = new Set(["apps/client/src/routeTree.gen.ts"]);
// Generated by Wrangler. Declaration files outside this exact allowlist remain
// subject to parsing, dependency checks, and the handwritten line ceiling.
export const generatedDeclarationPaths = new Set([
  "apps/agent/worker-configuration.d.ts",
  "apps/client/worker-configuration.d.ts",
  "apps/server/worker-configuration.d.ts",
]);
// Generated by shadcn and intentionally kept verbatim so updates remain diffable.
export const handwrittenLineLimitExceptions = new Set([
  "apps/client/src/components/ui/sidebar.tsx",
]);

// These files are intentionally split by domain responsibility. Their lower
// limits prevent the former all-in-one project brief schema/contract from
// gradually growing back below the repository-wide 500-line ceiling.
export const focusedFileLineLimits = new Map([
  ["packages/core/src/projects/definition.ts", 200],
  ["packages/core/src/projects/dto.ts", 200],
  ["packages/core/src/projects/generation.ts", 100],
  ["packages/core/src/projects/workflow.ts", 220],
  ["packages/orpc/src/projects/contract.ts", 250],
]);

// Canonical strings from packages/orpc/src/shared/errors.ts. Keep in sync by
// hand - this script has no import access to that module's runtime values.
export const sharedErrorMessages = [
  "ログインが必要です",
  "APIキーが無効です",
  "利用可能なワークスペースがありません",
  "許可されていないOriginです",
  "この操作を行う権限がありません",
  "施策ブリーフが見つかりません",
  "承認済みの施策ブリーフが必要です",
  "施策ブリーフのrevisionが一致しません",
  "現在の状態ではこの操作を実行できません",
  "施策ブリーフが更新されています。最新の内容を再読み込みしてください",
  "担当者または承認者が無効です",
];

// apps/server/src should read/write through packages/database repositories.
// This allowlist is a ratchet: shrink it as files migrate to a repository,
// never grow it for a new raw-drizzle call site.
export const drizzleImportAllowlist = [];
export const routeSsrFalseAllowlist = new Set([]);
export const migratedCommandRouters = new Set([
  "apps/server/src/web/router.ts",
  "apps/server/src/automations/router.ts",
  "apps/server/src/contacts/router.ts",
  "apps/server/src/segments/router.ts",
]);
