export const handwrittenFileLineLimit = 500;
export const clientFunctionLineLimit = 250;
// UI controllers extracted to .ts keep the component function ceiling.
export const clientControllerPattern = /^apps\/client\/src\/.+(?:\/|-)controller\.ts$/;
// Client UI areas already split into focused files; tighter limits keep them that way.
export const focusedClientUiFileLineLimit = 250;
export const focusedClientUiFunctionLineLimit = 120;
export const focusedClientUiPatterns = [
  /^apps\/client\/src\/components\/data-table(?:-[^/]+)?\.(?:ts|tsx)$/,
  /^apps\/client\/src\/features\/(?:companies|scoring|settings)\//,
  /^apps\/client\/src\/features\/contacts\/(?:contact-(?:drawer|profile|score|timeline))/,
  /^apps\/client\/src\/features\/emails\/email-(?:block|document)/,
  /^apps\/client\/src\/features\/segments\/segment-(?:builder|condition|filter-node|form)/,
  /^apps\/client\/src\/features\/website\/(?:custom-redirect|landing-page|resource-|signup-form|site-message)/,
];
// Generated by TanStack Router. Exact paths prevent a `.gen.*` rename from
// bypassing dependency, parser, file-size, and function-size enforcement.
export const generatedSourcePaths = new Set(["apps/client/src/routeTree.gen.ts"]);
// Generated by Wrangler. Declaration files outside this exact allowlist remain
// subject to parsing, dependency checks, and the handwritten line ceiling.
export const generatedDeclarationPaths = new Set([
  "apps/agent/worker-configuration.d.ts",
  "apps/client/worker-configuration.d.ts",
  "apps/server/worker-configuration.d.ts",
]);
// Generated by shadcn and intentionally kept verbatim so updates remain diffable.
export const handwrittenLineLimitExceptions = new Set([
  "apps/client/src/components/ui/sidebar.tsx",
]);

// These files are intentionally split by domain responsibility. Their lower
// limits prevent the former all-in-one project brief schema/contract from
// gradually growing back below the repository-wide 500-line ceiling.
export const focusedFileLineLimits = new Map([
  ["packages/core/src/projects/definition.ts", 200],
  ["packages/core/src/projects/dto.ts", 200],
  ["packages/core/src/projects/generation.ts", 100],
  ["packages/core/src/projects/workflow.ts", 220],
  ["packages/orpc/src/projects/contract.ts", 250],
]);

// Canonical strings from packages/orpc/src/shared/errors.ts. Keep in sync by
// hand - this script has no import access to that module's runtime values.
export const sharedErrorMessages = [
  "ログインが必要です",
  "APIキーが無効です",
  "利用可能なワークスペースがありません",
  "許可されていないOriginです",
  "この操作を行う権限がありません",
  "施策ブリーフが見つかりません",
  "承認済みの施策ブリーフが必要です",
  "施策ブリーフのrevisionが一致しません",
  "現在の状態ではこの操作を実行できません",
  "施策ブリーフが更新されています。最新の内容を再読み込みしてください",
  "担当者または承認者が無効です",
];

export const routeSsrFalseAllowlist = new Set([]);
// Server routers authorize and map errors; persistence belongs to services.
// Routers listed here still construct repositories. This is a ratchet: remove
// a router once it delegates to a service, never add a new one.
export const routerDatabaseImportAllowlist = new Set([
  "apps/server/src/agents/router.ts",
  "apps/server/src/automations/execution-router.ts",
  "apps/server/src/consent/router.ts",
  "apps/server/src/deals/sales-router.ts",
  "apps/server/src/messaging/router.ts",
  "apps/server/src/projects/clone-router.ts",
  "apps/server/src/projects/cost-router.ts",
  "apps/server/src/projects/program-router.ts",
  "apps/server/src/projects/router.ts",
  "apps/server/src/projects/variable-router.ts",
  "apps/server/src/reports/router.ts",
  "apps/server/src/scoring/router.ts",
  "apps/server/src/web/form-handler-router.ts",
  "apps/server/src/web/form-router.ts",
  "apps/server/src/web/landing-router.ts",
  "apps/server/src/web/optimization-router.ts",
  "apps/server/src/web/page-router.ts",
  "apps/server/src/web/redirect-router.ts",
  "apps/server/src/web/site-message-router.ts",
  "apps/server/src/web/tracking-router.ts",
]);
